DeployGate/deploygate-android-sdk

src/com/deploygate/sdk/DeployGate.java

If deploy gate is not avaiable on install, onInitialized(false) is called twice.
It may be an intentional behavior because first call of onInitialized(false) happens before returning from DeplayGate.install(...).
If so, please reject this PR.

fix duplicate onInitialized(false) call in DeployGate.install(...).

---

sdk/src/main/java/com/deploygate/sdk/DeployGate.java
sdk/src/main/java/com/deploygate/service/DeployGateEvent.java

The current DeployGate client app cannot report custom exceptions due to missing ClassLoader.
So sdk should change a way to report crashes
*Old method*
Just serialize a given throwable into an extra and emit it.
*New method*
Extract a root cause message and stacktraces. And then, store them to an extra and emit it.
*New method*
```
java.lang.IllegalStateException: Could not execute method for android:onClick
at android.view.View$DeclaredOnClickListener.onClick(View.java:4700)
at android.view.View.performClick(View.java:5612)
at android.view.View$PerformClick.run(View.java:22288)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123) …
```

Stop sending custom exceptions with serializing them

---

.gitignore
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
sdk.build.gradle
sdk/build.gradle
sdkMock/build.gradle

Fixed #23 
`com.novoda:bintray-release` doesn't append several fields to pom files by design.

Fixed generated pom files didn't include license and so on

---

build.gradle
sdk.build.gradle

Close #25 
Android classpath has been excluded from each classpath of variants so we need to add it explicitly.

Added a workaround to generate javadocs with Android Gradle Plugin 3.6.x

---

build.gradle
sample/build.gradle
sdk/src/main/AndroidManifest.xml

As Package Visibility changes, the explicit package element is required to bind the service of DeployGate client app.
This change will build the sample project with Android R so AGP version needs to be upgraded to 3.6.1 or higher.

Support Android 11's PackageVisibility

---

.circleci/config.yml
README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
publishing.build.gradle
release.sh
sdk.build.gradle
sdk/build.gradle
sdk/src/main/java/com/deploygate/sdk/DeployGate.java
sdkMock/build.gradle

No code changes.
- Tweaked README
- Bumped up version
- Upgraded AGP. 
- Rewriting the maven publishing configuration is required because Gradle 6.0, which the new AGP depends on, breaks https://github.com/novoda/bintray-release compatibility but they haven't merged the fixing.

Prepare for 4.3.0 release which supports target sdk version 30

---

sdk/src/main/java/com/deploygate/sdk/Compatibility.java
sdk/src/main/java/com/deploygate/sdk/CustomLog.java
sdk/src/main/java/com/deploygate/sdk/DeployGate.java
sdk/src/main/java/com/deploygate/service/DeployGateEvent.java
sdk/src/test/java/com/deploygate/sdk/CustomLogTest.java

This measuring relies on `SystemClock.elapsedRealtime` so it's available only for on-memory buffer.

Measure and send buffered-time in on-memory buffer to the remote service

---

sdk/build.gradle
sdk/src/main/java/com/deploygate/sdk/CustomLog.java
sdk/src/main/java/com/deploygate/sdk/CustomLogInstructionSerializer.java
sdk/src/main/java/com/deploygate/sdk/DeployGate.java
sdk/src/main/java/com/deploygate/sdk/UniqueId.java
sdk/src/main/java/com/deploygate/service/DeployGateEvent.java
sdk/src/test/java/com/deploygate/sdk/CustomLogInstructionSerializerTest.java
sdk/src/test/java/com/deploygate/sdk/CustomLogTest.java

As for the current events, the consistency is guaranteed but the further events may not have. So, the data provider should generate the unique id for each events to keep data inconsistency between the single AIDL transaction. 
fix: https://github.com/DeployGate/deploygate-android-sdk/issues/57

Send the unique id to identify the event (data)

---

sample/src/main/java/com/deploygate/sample/SampleActivity.java
sdk.build.gradle
sdk/src/main/java/com/deploygate/sdk/CustomLogInstructionSerializer.java
sdk/src/main/java/com/deploygate/sdk/DeployGate.java
sdk/src/main/java/com/deploygate/sdk/ILogcatInstructionSerializer.java
sdk/src/main/java/com/deploygate/sdk/LogcatInstructionSerializer.java
sdk/src/main/java/com/deploygate/sdk/LogcatProcess.java
sdk/src/main/java/com/deploygate/sdk/SendLogcatRequest.java
sdk/src/main/java/com/deploygate/sdk/internal/Factory.java
sdk/src/main/java/com/deploygate/service/DeployGateEvent.java
sdk/src/test/java/com/deploygate/sdk/CustomLogInstructionSerializerTest.java
sdk/src/test/java/com/deploygate/sdk/LogcatInstructionSerializerTest.java
sdk/src/test/java/com/deploygate/sdk/LogcatProcessTest.java
sdk/src/test/java/com/deploygate/sdk/SendLogcatRequestTest.java
sdk/src/test/java/com/deploygate/sdk/helper/FakeLogcat.java

This changeset serializes the instruction for sending Logcat data to the remove service. 
ref: https://github.com/DeployGate/deploygate-android-sdk/issues/48
We should buffer the instruction for sending one chunk of lines to the remote service but not for starting Logcat process because Logcat is launchable regardless of the client app's availability.
```mermaid
sequenceDiagram
participant Logcat
participant Reader (SDK)
participant Serializer (SDK)
participant ClientApp
Reader (SDK)->>Logcat: Create a process
Logcat->>Logcat: Generate the bundle id
loop Streaming
Logcat->>Reader (SDK): Read and pack lines as a chunk
end
Reader (SDK)-->>Serializer (SDK): Enqueue the send-instruction on every chunk
Serializer (SDK)->>Serializer (SDK): Serialize and process the instructions
Serializer …
```

Buffer Logcat instructions

---

sdk.build.gradle
sdk/src/main/AndroidManifest.xml
sdk/src/main/java/com/deploygate/sdk/Compatibility.java
sdk/src/main/java/com/deploygate/sdk/DeployGate.java
sdk/src/main/java/com/deploygate/sdk/DeployGateClient.java
sdk/src/main/java/com/deploygate/sdk/HostApp.java
sdk/src/main/java/com/deploygate/sdk/LogcatInstructionSerializer.java
sdk/src/main/java/com/deploygate/service/DeployGateEvent.java
sdk/src/test/java/com/deploygate/sdk/CompatibilityTest.java
sdk/src/test/java/com/deploygate/sdk/DeployGateClientTest.java
sdk/src/test/java/com/deploygate/sdk/DeployGateInterfaceTest.java
sdk/src/test/java/com/deploygate/sdk/HostAppTest.java
sdk/src/test/java/com/deploygate/sdk/LogcatInstructionSerializerTest.java
sdkMock/src/main/java/com/deploygate/sdk/DeployGate.java

As for several values, we don't need to wait for the callback response from the client app.
- Embed the sdk version in the manifest file.
- This means the client app can know the version before getting a reply from SDK. No problem even if it's faked. (It's possible to fake the value on the current implementation in the first place.)
- The client app will tell SDK about supported features through metadata.
- Use bit operators to reduce the metadata size
- Now SDK don't need to know which version has the feature compatibility.

Use metadata to get static values

---

sdk/src/main/java/com/deploygate/sdk/CustomLogConfiguration.java
sdk/src/main/java/com/deploygate/sdk/LogcatProcess.java
sdk/src/main/java/com/deploygate/sdk/internal/annotations/Experimental.java

The new annotations are just markers. They are not like Kotlin's experimental API unfortunately but it would be better to have them in our code.

Annotate experimental elements with new annotations

---

publishing.build.gradle
scripts/release.sh

Aggregation tasks had disappeared? We should use publishReleasePublicationToMavenRepository anyway.

Use publishReleasePublicationToMavenRepository to publish release artifacts

---

.github/workflows/deploy-javadoc.yml

It will fail since June 1st as https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ announced.

Use GITHUB_OUTPUT instead of set-output command

---

.circleci/config.yml
.github/workflows/release.yml
.github/workflows/test.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
sample/build.gradle
sdk.build.gradle
sdk/src/main/java/com/deploygate/sdk/DeployGate.java

This feature has been introduced since Android 13 SDK (https://developer.android.com/about/versions/13/features#runtime-receivers) and it's now required for apps that target Android 14 or later (https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported).
See the implementation of ContextCompat for the verification. https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/content/ContextCompat.java;drc=b63ff8c4299a6486bf34ec2ac746517e2d378d43

Specify export flag for Context-based receiver

---

README.md

- modified sample code in the README for use `sdk` and `sdk-mock` properly and make get started more easier.
- add sample code when initialising the DeployGate SDK manually.

Proposal: Update README for use `sdk` and `sdk-mock` more properly

---

sdk/src/main/java/com/deploygate/sdk/DeployGateClient.java
sdk/src/main/java/com/deploygate/sdk/internal/Logger.java

We already put `query` tag to look up com.deploygate application, so metaData must be present. However, one device reported this strange behaviour. I couldn't identify why this occurred though, let me add a patch to fit it anyway.

A few device may not be able to read metaData of DeployGate application

---

build.gradle
sdk.build.gradle
sdk/src/main/AndroidManifest.xml
sdk/src/main/java/com/deploygate/sdk/DeployGate.java
sdk/src/main/java/com/deploygate/sdk/HostApp.java
sdk/src/main/java/com/deploygate/service/DeployGateEvent.java
sdk/src/test/java/com/deploygate/sdk/HostAppTest.java

This is useful for host apps to control SDK functionalities more flexible.
NOTE: This can be overridden by developers, however, there is no problem cuz this is not an authentication/authorization stuff. Such cheat wouldn't bring any benefit to developers but may cause app crashes or unexpected behaviours.

Embed SDK's artifact version in meta-data tags

---

sdk/src/main/java/com/deploygate/sdk/DeployGate.java
sdk/src/main/java/com/deploygate/sdk/DeployGateSdkConfiguration.java
sdk/src/main/java/com/deploygate/sdk/HostApp.java
sdk/src/main/java/com/deploygate/service/DeployGateEvent.java
sdk/src/test/java/com/deploygate/sdk/HostAppTest.java

Close #68
We should provide flexible configuration for users. Especially, opting-out data collection is getting important. Some of features are triggered by our client app, so SDK state must be delivered to our app through AIDL; We can know the active features from *init* event.

Provide opt-out for crash reporting and device capture features

---

build.gradle
sdk/src/test/java/com/deploygate/sdk/HostAppTest.java

Tweaked a few testcase to use bit flags instead of the constant value.

Bump to 4.7.0

---

.github/workflows/deploy-javadoc.yml

Close #40
The current workflow just downloads the latest release and it's basically enough if no issue occurred ever. This change fixes it to check all releases on every workflow run.

Download and unarchive all javadocs which are missing at a run-time

---

sdk/src/test/java/com/deploygate/sdk/DeployGateInterfaceTest.java
sdkMock/src/main/java/com/deploygate/sdk/DeployGate.java
sdkMock/src/main/java/com/deploygate/sdk/DeployGateSdkConfiguration.java

Close #83 
DeployGateSdkConfiguration class and DeployGate#install method appears only in com.deploygate.sdk artifact so those who use the entities would be faced with compilation errors on variants that use sdk-mock dependency.
This PR adds the classes above to sdkMock module as well.
BTW, to solve this issue completely, we must introduce automated code-generation tool to produce sdkMock classes instead of maintaining independently.

Add DeployGateSdkConfiguration class and DeployGate#install to sdkMock

---

.github/workflows/test.yml
plugins/library/build.gradle.kts
plugins/library/src/main/java/com/deploygate/plugins/BaseSdkPlugin.kt
plugins/library/src/main/java/com/deploygate/plugins/MavenPublishPlugin.kt
plugins/library/src/main/java/com/deploygate/plugins/SdkMockPlugin.kt
plugins/library/src/main/java/com/deploygate/plugins/SdkPlugin.kt
plugins/library/src/main/java/com/deploygate/plugins/dsl/SdkExtension.kt
plugins/library/src/main/java/com/deploygate/plugins/internal/SdkExtensionImpl.kt
plugins/library/src/main/java/com/deploygate/plugins/internal/SdkMetaData.kt
plugins/library/src/main/java/com/deploygate/plugins/tasks/GenerateMetaDataJsonTask.kt
sdk/build.gradle
sdk/src/main/AndroidManifest.xml
sdkMock/build.gradle

The current sdk-mock doesn't contain meta-data, however, they would be accidentally included due to human errors. We should make sure that meta-data should appear only in sdk. And also, it should be visualised for the maintainability reason.

Never add meta-data to sdk-mock and visualize meta-data in JSON format on CI

---

plugins/library/src/main/java/com/deploygate/plugins/BaseSdkPlugin.kt
sample/src/main/AndroidManifest.xml
sample/src/main/java/com/deploygate/sample/App.java
sample/src/main/java/com/deploygate/sample/SampleActivity.java
sdk/src/main/java/com/deploygate/sdk/CustomAttributes.java
sdk/src/main/java/com/deploygate/sdk/DeployGate.java
sdk/src/main/java/com/deploygate/service/DeployGateEvent.java
sdk/src/test/java/com/deploygate/sdk/CustomAttributesInterfaceTest.java
sdk/src/test/java/com/deploygate/sdk/CustomAttributesTest.java
sdk/src/test/java/com/deploygate/sdk/DeployGateInterfaceTest.java
sdk/src/test/java/com/deploygate/sdk/HostAppTest.java
sdkMock/src/main/java/com/deploygate/sdk/CustomAttributes.java
sdkMock/src/main/java/com/deploygate/sdk/DeployGate.java
sdkMock/src/test/java/com/deploygate/sdk/CustomAttributesInterfaceTest.java

I added an implementation that will be used to enhance the capture function provided after the next version.
- Users can add attributes freely and their values via `CustomAttributes` class .
- Attributes are divided into two groups. `BuildEnvironment` or `RuntimeExtra`.
- DeployGate instance keeps `CustomAttriutes` of each groups.
- The attributes are sent automatically to DeployGate by SDK when the capture is created.
- When SDK received `ACTION_COLLECT_DEVICE_STATES` event, SDK will write values via content provider.

Collect and send custom attributes for capture feature

---

sample/src/main/java/com/deploygate/sample/SampleActivity.java
sdk/src/main/java/com/deploygate/sdk/DeployGate.java

I consider this log should be removed as it contains content URI and verbose-level logs.

Fix: Delete an unnecessary log and blank lines

---

.github/workflows/release.yml

According to [the notice from sonatype](https://central.sonatype.org/news/20240617_migration_of_accounts/#the-impact-on-ossrh-and-the-central-publisher-portal), we cannot use username and password when uploading artifacts to the repository.
So, we should use a user token in our GitHub Actions workflow.
Ref. https://central.sonatype.org/news/20240617_migration_of_accounts/#the-impact-on-ossrh-and-the-central-publisher-portal

Fix: use sonatype user token for uploading artifacts

---

.github/workflows/release.yml

Workflow of `Release artifacts` was failed with `java.lang.OutOfMemoryError: Metaspace`.
But the workflow of `Build and test projects` was successful.
`Build and test projects` has `GRADLE_OPTS` env and defined max size of Java heap memory and metaspace for the gradle deamon.
So, I think we can fix this by setting `GRADLE_OPTS` in your workflow file.

Fix: set GRADLE_OPTS to avoid causing OOM when upload artifacts

---

sample/src/main/java/com/deploygate/sample/App.java
sample/src/main/java/com/deploygate/sample/SampleActivity.java
sdk/src/main/java/com/deploygate/sdk/DeployGate.java
sdk/src/main/java/com/deploygate/sdk/DeployGateCaptureCreateCallback.java
sdk/src/main/java/com/deploygate/sdk/DeployGateSdkConfiguration.java
sdk/src/main/java/com/deploygate/service/DeployGateEvent.java
sdk/src/test/java/com/deploygate/sdk/DeployGateInterfaceTest.java
sdk/src/test/java/com/deploygate/sdk/DeployGateSdkConfigurationInterfaceTest.java
sdk/src/test/java/com/deploygate/sdk/DeployGateSdkConfigurationTest.java
sdk/src/test/java/com/deploygate/sdk/DeployGateTest.java
sdkMock/src/main/java/com/deploygate/sdk/DeployGate.java
sdkMock/src/main/java/com/deploygate/sdk/DeployGateCaptureCreateCallback.java
sdkMock/src/main/java/com/deploygate/sdk/DeployGateSdkConfiguration.java

We provide the callback interface to notify of finished create the Capture.
You can trigger any process when the Capture is successfully created.
e.g. logging application states, saving snapshot data, etc...

Add new callback interface to receive the Capture creation event

---

sdk/src/main/java/com/deploygate/sdk/DeployGate.java
sdk/src/main/java/com/deploygate/sdk/SdkDeviceStatesCollector.java

Collect any device states when creating a capture.
Some attributes are collected on the host app better correctly.
(e.g. per-app language preference: https://developer.android.com/guide/topics/resources/app-languages?hl=ja )

feat: collecting device states on SDK

---

sdk/src/main/java/com/deploygate/sdk/SdkDeviceStatesCollector.java

fix https://github.com/DeployGate/deploygate-android-sdk/pull/98#issuecomment-2359995916
> SdkDeviceStatesCollector should be thread-safe for reading/writing attributes.

read/write to JSONObject with thread-safe

---

sample/build.gradle

Closing #100 
We need to use the latest version SDK when build sample app with `stable` flavors.

Fix: failure to build a sample app with stable flavors

---

gradle.properties

Already fixed to avoid causing OOM when upload artifacts for GitHub Actions. #92 
But we encountered again in the other environment.

chore: set some params in gradle.properties

---

sdk/src/main/java/com/deploygate/sdk/CustomAttributes.java
sdk/src/test/java/com/deploygate/sdk/CustomAttributesTest.java

Closing #104 
Relaxed restriction max size of custom attributes according to the issue #104.

chore: easing restriction max size of custom attributes
